# Generated by Django 5.1.7 on 2025-03-08 13:23

import destination_app.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[destination_app.validators.validate_website]),
        ),
    ]
