# Generated by Django 5.1.7 on 2025-03-08 13:24

import destination_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0002_alter_account_app_secret_token_alter_account_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[destination_app.validators.validate_email]),
        ),
    ]
