# Generated by Django 5.1.7 on 2025-03-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Normal user', 'Normal user')], default='Normal user', max_length=20),
        ),
    ]
